name: audio_service_667
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  just_audio: 0.7.4
  audio_service:
    git: # patch
      url: https://github.com/nt4f04und/audio_service.git
      ref: multithread # 2a594beca4e2a95ee5d1d16dde7c17d9ef636c9e
      path: audio_service

    # git: # upstream
    #   url: https://github.com/ryanheise/audio_service.git
    #   ref: one-isolate # a8a567719bd8f9b579952ce7fb984d7f495b069a
    #   path: audio_service
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
