name: audio_service_671
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  quick_actions: ^0.6.0
  just_audio: ^0.7.5
  # audio_service:
  #   git:
  #     url: https://github.com/ryanheise/audio_service.git
  #     ref: 56477c2ba066f6dfb89dfa970e47aa2651e0f3c1 # crashy version
  #     path: audio_service
  audio_service:
    git:
      url: https://github.com/nt4f04und/audio_service.git
      ref: 59b74f1734fe57b647cbb90f7bc0caa269186b40 # fixed version
      path: audio_service
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
