name: audio_service_784
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  just_audio: 0.7.4
  audio_service:
    git:
      url: https://github.com/ryanheise/audio_service.git
      ref: 02ed2e8b3a242cae81e1a5d2c369afb96dcee149 # one-isolate
      path: audio_service
  # audio_service:
  #   path: C:/dev/projects/native/audio_service/audio_service
  flutter_audio_query: ^0.3.5+6
  permission_handler: ^8.1.2
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
