name: audio_service_690
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  just_audio: 0.7.4
  audio_service:
    git:
      url: https://github.com/ryanheise/audio_service.git
      ref: d83855dd6eee73a5e86ba6e2794bc8045cda2235 # one-isolate
      path: audio_service
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
