name: flutter_issue72508
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # video_player: ^2.0.2
  video_player:
    git:
      url: https://github.com/flutter/plugins
      path: packages/video_player/video_player
      ref: faa26ec364cd6d3c738d73526ea55a95b7f4ab1a
  # video_player:
  #   path: /Users/danya/dev/projects/plugins/packages/video_player/video_player
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/