name: flutter_78169
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  video_player: 2.0.0-nullsafety.10
  # video_player: # if you use this version memory usage increases
  #   git:
  #     url: https://github.com/flutter/plugins
  #     path: packages/video_player/video_player
  #     ref: fa95cde0781289ef6918ecc287bfa63d4736bf1f
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/